FROM public.ecr.aws/lambda/python:3.9

# install dependencies
COPY requirements.lambda.txt  .
RUN pip install --no-cache-dir -r requirements.lambda.txt

# copy code
COPY src/ ${LAMBDA_TASK_ROOT}/src/
COPY src/config.py ${LAMBDA_TASK_ROOT}/config.py

# set handler
CMD ["src/fetch_jobs.handler"]
